### ISSUE TITLE
Add content to our front page

### ISSUE THREAD

**Issue by Copposhop** [CAuDri/caudri.github.io#7]
Maybe a list of necessary steps to compete at the competition? Like:
- Build your own vehicle
- Let it perceive its environment
- Let it decive what to do
- Compare to other teams
Each with a short  description and an image.

**Comment by Jajaho** [comment]
Maybe we dedicate a separate page to this getting started content, we can link to it using a widget.

**Comment by Jajaho** [comment]
#16

**Comment by Jajaho** [comment]
Merged #16
